name: 中国联通自动签到

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'  # 每天UTC 0点执行（北京时间8:00）

jobs:
  signin:
    runs-on: ubuntu-latest
    steps:
      - name: 检出代码
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: 安装依赖
        run: |
          pip install pycryptodome==3.20.0
          pip install requests==2.31.0

      - name: 执行签到
        env:
          USER: ${{ secrets.USER }}  # 格式：手机号1,密码1\n手机号2,密码2
          APPID: ${{ secrets.APPID }}  # 需抓包获取最新160位十六进制字符串
        run: |
          # APPID格式验证[1,5](@ref)
          if [[ -z "$APPID" || ${#APPID} -ne 160 || ! "$APPID" =~ ^[0-9a-f]+$ ]]; then
            echo "::error::APPID格式错误：必须为160位十六进制字符串"
            exit 1
          fi

          IFS=$'\n'  # 多账号换行分隔[7](@ref)
          for account in $USER; do
            IFS=',' read -r phone password <<< "$account"
            
            # 密码有效性验证[4](@ref)
            if [[ -z "$password" || "$password" == *" "* ]]; then
              echo "::error::手机号 $phone 密码格式错误（含空格或为空）"
              continue
            fi

            output=$(python3 CnUnicom.py "$phone" "$password" "$APPID" 2>&1)
            
            # 错误类型判断[4,5](@ref)
            if [[ "$output" == *"login failed"* ]]; then
              echo "::error::手机号 $phone 服务密码错误"
            elif [[ "$output" == *"appid invalid"* ]]; then
              echo "::error::APPID失效，请重新抓取"
              exit 1
            elif [[ "$output" == *"Success"* ]]; then
              echo "✅ $phone 签到成功"
              echo "$output" | grep -E "获得积分|奖励详情"
            else
              echo "::warning::未知错误：$output"
            fi
          done

      - name: 上传日志
        uses: actions/upload-artifact@v4
        with:
          name: signin-log
          path: ${{ github.workflow }}-log.txt
